package com.ffcs.entity;

import javax.persistence.*;

@Table(name = "`game_reaction`")
public class GameReaction {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_reaction.id
     *
     * @mbg.generated Thu Aug 09 19:04:20 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_reaction.userid
     *
     * @mbg.generated Thu Aug 09 19:04:20 CST 2018
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_reaction.times
     *
     * @mbg.generated Thu Aug 09 19:04:20 CST 2018
     */
    private String times;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_reaction.times_int
     *
     * @mbg.generated Thu Aug 09 19:04:20 CST 2018
     */
    private Integer timesInt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_reaction.rank
     *
     * @mbg.generated Thu Aug 09 19:04:20 CST 2018
     */
    private Integer rank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_reaction.ctime
     *
     * @mbg.generated Thu Aug 09 19:04:20 CST 2018
     */
    private Integer ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_reaction.mtime
     *
     * @mbg.generated Thu Aug 09 19:04:20 CST 2018
     */
    private Integer mtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_reaction.status
     *
     * @mbg.generated Thu Aug 09 19:04:20 CST 2018
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_reaction.id
     *
     * @return the value of game_reaction.id
     *
     * @mbg.generated Thu Aug 09 19:04:20 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_reaction.id
     *
     * @param id the value for game_reaction.id
     *
     * @mbg.generated Thu Aug 09 19:04:20 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_reaction.userid
     *
     * @return the value of game_reaction.userid
     *
     * @mbg.generated Thu Aug 09 19:04:20 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_reaction.userid
     *
     * @param userid the value for game_reaction.userid
     *
     * @mbg.generated Thu Aug 09 19:04:20 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_reaction.times
     *
     * @return the value of game_reaction.times
     *
     * @mbg.generated Thu Aug 09 19:04:20 CST 2018
     */
    public String getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_reaction.times
     *
     * @param times the value for game_reaction.times
     *
     * @mbg.generated Thu Aug 09 19:04:20 CST 2018
     */
    public void setTimes(String times) {
        this.times = times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_reaction.times_int
     *
     * @return the value of game_reaction.times_int
     *
     * @mbg.generated Thu Aug 09 19:04:20 CST 2018
     */
    public Integer getTimesInt() {
        return timesInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_reaction.times_int
     *
     * @param timesInt the value for game_reaction.times_int
     *
     * @mbg.generated Thu Aug 09 19:04:20 CST 2018
     */
    public void setTimesInt(Integer timesInt) {
        this.timesInt = timesInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_reaction.rank
     *
     * @return the value of game_reaction.rank
     *
     * @mbg.generated Thu Aug 09 19:04:20 CST 2018
     */
    public Integer getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_reaction.rank
     *
     * @param rank the value for game_reaction.rank
     *
     * @mbg.generated Thu Aug 09 19:04:20 CST 2018
     */
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_reaction.ctime
     *
     * @return the value of game_reaction.ctime
     *
     * @mbg.generated Thu Aug 09 19:04:20 CST 2018
     */
    public Integer getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_reaction.ctime
     *
     * @param ctime the value for game_reaction.ctime
     *
     * @mbg.generated Thu Aug 09 19:04:20 CST 2018
     */
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_reaction.mtime
     *
     * @return the value of game_reaction.mtime
     *
     * @mbg.generated Thu Aug 09 19:04:20 CST 2018
     */
    public Integer getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_reaction.mtime
     *
     * @param mtime the value for game_reaction.mtime
     *
     * @mbg.generated Thu Aug 09 19:04:20 CST 2018
     */
    public void setMtime(Integer mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_reaction.status
     *
     * @return the value of game_reaction.status
     *
     * @mbg.generated Thu Aug 09 19:04:20 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_reaction.status
     *
     * @param status the value for game_reaction.status
     *
     * @mbg.generated Thu Aug 09 19:04:20 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}